conn yplaza-agency01
  left=%defaultroute
  leftid=@hq.yplaza.local
  right=198.51.100.10
  rightid=@agency01.yplaza.local
  leftsubnet=10.10.0.0/16
  rightsubnet=10.20.1.0/24
  ike=aes256-sha256-modp2048
  esp=aes256-sha256
  keyexchange=ikev2
  dpdaction=restart
  dpddelay=30s
  rekey=yes
  auto=start

conn yplaza-agency02
  left=%defaultroute
  leftid=@hq.yplaza.local
  right=198.51.100.11
  rightid=@agency02.yplaza.local
  leftsubnet=10.10.0.0/16
  rightsubnet=10.20.2.0/24
  ike=aes256-sha256-modp2048
  esp=aes256-sha256
  keyexchange=ikev2
  dpdaction=restart
  dpddelay=30s
  rekey=yes
  auto=add
